# Build the installer  ->  AnkiAssistant-Setup.exe
# Usage: powershell -ExecutionPolicy Bypass -File build-setup.ps1
#
# The installer is a single self-contained exe: the main program, its icon and the
# changelog are embedded as resources, so there is nothing else to download.
#
# NOTE: keep this file ASCII-only (PowerShell 5.1 reads .ps1 as ANSI without a BOM).
$ErrorActionPreference = "Stop"

$here    = Split-Path -Parent $MyInvocation.MyCommand.Path
$appDir  = Join-Path (Split-Path -Parent $here) "AnkiAssistant"
$csc     = "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if (-not (Test-Path $csc)) { $csc = "C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe" }
if (-not (Test-Path $csc)) { throw "csc.exe not found" }

# ---- version comes from the app source, so installer and app can never drift apart
$ghPath = Join-Path $appDir "src\GitHub.cs"
if (-not (Test-Path $ghPath)) { throw "missing input: $ghPath" }
$gh = Get-Content $ghPath -Raw
if ($gh -match 'VersionTag\s*=\s*"v?([0-9][^"]*)"') { $ver = $Matches[1] }
else { throw "cannot parse VersionTag from GitHub.cs" }
Write-Host "version: $ver"

# ---- the main program must be built first; try the app's own build.ps1 once
$exe = Join-Path $appDir "AnkiAssistant.exe"
if (-not (Test-Path $exe)) {
    $appBuild = Join-Path $appDir "build.ps1"
    if (Test-Path $appBuild) {
        Write-Host "AnkiAssistant.exe not found - running the app build first:"
        Write-Host "  $appBuild"
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $appBuild
    }
    if (-not (Test-Path $exe)) {
        throw ("missing input: $exe" + [Environment]::NewLine +
               "build the main program first:  powershell -ExecutionPolicy Bypass -File `"$appBuild`"")
    }
}

# ---- remaining inputs must exist
$repoRoot = Split-Path -Parent $here
$ico   = Join-Path $appDir "assets\app.ico"
$chg   = Join-Path $repoRoot "CHANGELOG.md"
foreach ($p in @($exe, $ico, $chg)) {
    if (-not (Test-Path $p)) { throw "missing input: $p" }
}

# ---- generate SetupInfo.cs
$out = Join-Path $here "build"
if (Test-Path $out) { Remove-Item -Recurse -Force $out }
New-Item -ItemType Directory -Force $out | Out-Null

$info = @"
// AUTO-GENERATED by build-setup.ps1 -- do not edit
namespace AnkiAssistant.Setup
{
    public static class SetupInfo
    {
        public const string Version = "$ver";
    }
}
"@
Set-Content -Path (Join-Path $out "SetupInfo.cs") -Value $info -Encoding UTF8

# ---- compile
$srcs = @(Get-ChildItem (Join-Path $here "src") -Filter *.cs | ForEach-Object { $_.FullName })
$srcs += (Join-Path $out "SetupInfo.cs")

$target = Join-Path $here "AnkiAssistant-Setup.exe"
if (Test-Path $target) { Remove-Item $target -Force }

& $csc /nologo /codepage:65001 /target:winexe /optimize+ /out:$target `
    /win32icon:$ico `
    "/resource:$exe,App.AnkiAssistant.exe" `
    "/resource:$ico,App.app.ico" `
    "/resource:$chg,App.CHANGELOG.md" `
    /r:System.dll /r:System.Drawing.dll /r:System.Windows.Forms.dll /r:System.Core.dll `
    $srcs

if ($LASTEXITCODE -ne 0) { throw "compile failed" }

$kb = [math]::Round((Get-Item $target).Length / 1KB, 1)
Write-Host "OK -> $target" -ForegroundColor Green
Write-Host ("size: {0:N0} KB" -f ((Get-Item $target).Length / 1KB))
